### ISSUE TITLE
PHP Warning: Undefined variable $links and PHP Fatal error:  Uncaught TypeError: ($media) must be of type array

### ISSUE THREAD

**Issue by mrdotx** [aledeg/xExtension-RedditImage#12]
Hi,

I have some new warnings/errors spamming my log ;)

```bash
Apr 06 03:28:08 m625q php[23764]: PHP Warning:  Undefined variable $links in /usr/share/webapps/freshrss/extensions/_xExtensions_git/xExtension-RedditImage/Transformer/InsertTransformer.php on line 145
Apr 06 03:28:08 m625q php[23764]: PHP Fatal error:  Uncaught TypeError: RedditImage\Transformer\AbstractTransformer::generateDom(): Argument #2 ($media) must be of type array, null given, called in /usr/share/webapps/freshrss/extensions/_xExtensions_git/xExtension-RedditImage/Transformer/InsertTransformer.php on line 145 and defined in /usr/share/webapps/freshrss/extensions/_xExtensions_git/xExtension-RedditImage/Transformer/AbstractTransformer.php:32
```

**Comment by aledeg** [comment]
Thank you.
I will look into that. Is there any chance you can provide me with a feed that generate such warnings and errors? That would be greatly appreciated.

**Comment by mrdotx** [comment]
I have extracted the complete trace from the log:

```bash
Apr 06 03:28:07 m625q systemd[1]: Started FreshRSS get new content.
Apr 06 03:28:07 m625q FreshRSS[23764]: FreshRSS starting feeds actualization at 2023-04-06T01:28:07+00:00
Apr 06 03:28:07 m625q php[23764]: FreshRSS starting feeds actualization at 2023-04-06T01:28:07+00:00
Apr 06 03:28:07 m625q FreshRSS[23764]: FreshRSS actualize syncuser…
Apr 06 03:28:07 m625q php[23764]: FreshRSS actualize syncuser…
Apr 06 03:28:07 m625q FreshRSS[23764]: SimplePie GET https://www.reddit.com/r/vim/.rss
Apr 06 03:28:08 m625q FreshRSS[23764]: SimplePie MD5 cache match for https://www.reddit.com/r/vim/.rss
Apr 06 03:28:08 m625q php[23764]: PHP Warning:  Undefined variable $links in /usr/share/webapps/freshrss/extensions/_xExtensions_git/xExtension-RedditImage/Transformer/InsertTransformer.php on line 145
Apr 06 03:28:08 m625q php[23764]: PHP Fatal error:  Uncaught TypeError: RedditImage\Transformer\AbstractTransformer::generateDom(): Argument #2 ($media) must be of type array, null given, called in /usr/share/webapps/freshrss/extensions/_xExtensions_git/xExtension-RedditImage/Transformer/InsertTransformer.php on line 145 and defined in /usr/share/webapps/freshrss/extensions/_xExtensions_git/xExtension-RedditImage/Transformer/AbstractTransformer.php:32
Apr 06 03:28:08 m625q php[23764]: Stack trace:
Apr 06 03:28:08 m625q php[23764]: #0 /usr/share/webapps/freshrss/extensions/_xExtensions_git/xExtension-RedditImage/Transformer/InsertTransformer.php(145): RedditImage\Transformer\AbstractTransformer->generateDom()
Apr 06 03:28:08 m625q php[23764]: #1 /usr/share/webapps/freshrss/lib/Minz/ExtensionManager.php(338): RedditImage\Transformer\InsertTransformer->transform()
Apr 06 03:28:08 m625q php[23764]: #2 /usr/share/webapps/freshrss/lib/Minz/ExtensionManager.php(309): Minz_ExtensionManager::callOneToOne()
Apr 06 03:28:08 m625q php[23764]: #3 /usr/share/webapps/freshrss/app/Controllers/feedController.php(483): Minz_ExtensionManager::callHook()
Apr 06 03:28:08 m625q php[23764]: #4 /usr/share/webapps/freshrss/app/Controllers/feedController.php(653): FreshRSS_feed_Controller::actualizeFeed()
Apr 06 03:28:08 m625q php[23764]: #5 /usr/share/webapps/freshrss/lib/Minz/Dispatcher.php(119): FreshRSS_feed_Controller->actualizeAction()
Apr 06 03:28:08 m625q php[23764]: #6 /usr/share/webapps/freshrss/lib/Minz/Dispatcher.php(46): Minz_Dispatcher->launchAction()
Apr 06 03:28:08 m625q php[23764]: #7 /usr/share/webapps/freshrss/lib/Minz/FrontController.php(58): Minz_Dispatcher->run()
Apr 06 03:28:08 m625q php[23764]: #8 /usr/share/webapps/freshrss/app/actualize_script.php(83): Minz_FrontController->run()
Apr 06 03:28:08 m625q php[23764]: #9 {main}
Apr 06 03:28:08 m625q php[23764]:   thrown in /usr/share/webapps/freshrss/extensions/_xExtensions_git/xExtension-RedditImage/Transformer/AbstractTransformer.php on line 32
Apr 06 03:28:08 m625q php[23764]: Results:
Apr 06 03:28:08 m625q php[23764]: syncuser
Apr 06 03:28:08 m625q systemd[1]: freshrss.service: Main process exited, code=exited, status=255/EXCEPTION
Apr 06 03:28:08 m625q systemd[1]: freshrss.service: Failed with result 'exit-code'.
```

Apparently the 'vim' feed is the culprit. However there is no problem at the moment. Since 1-2 days the error messages are gone. Maybe a temporary data integrity problem?

**Comment by aledeg** [comment]
Thank you. I will look into that.

**Comment by aledeg** [comment]
This is fixed. It will be available in the next release.
