### ISSUE TITLE
InvalidContentException

### ISSUE THREAD

**Issue by yunesj** [aledeg/xExtension-RedditImage#16]
I'm seeing the following error in the logs on a new installation. I think the extension is working for most other posts. Thanks!

```
RedditImage\Exception\InvalidContentException: submitted by <a href="https://www.reddit.com/user/Improv92"> /u/Improv92 </a> to <a href="https://www.reddit.com/r/AskReddit/"> r/AskReddit </a> <br> <span><a href="https://www.reddit.com/r/AskReddit/comments/18m8m16/what_do_poor_countries_do_better_than_rich/">[link]</a></span> <span><a href="https://www.reddit.com/r/AskReddit/comments/18m8m16/what_do_poor_countries_do_better_than_rich/">[comments]</a></span> in /var/www/FreshRSS/extensions/xExtension-RedditImage-1.1.1/Content.php:28
```

**Comment by aledeg** [comment]
Do you still have this issue?
Could you share the failing data?

Thank you!

**Comment by yunesj** [comment]
Yes, I'm still getting the error. Here's an example with a stack trace:

```
 FreshRSS[39]: [jeff] [Tue, 30 Sep 2025 01:15:11 -0400] [error] --- RedditImage\Exception\InvalidContentException:
 
 <div class="reddit-image figure"><!--xExtension-RedditImage/1.2.0 | RedditImage\Processor\BeforeInsertProcessor | RedditImage\Transformer\Reddit\GalleryTransformer--><img src="https://i.redd.it/nza8k7sg07sf1.jpg" class="reddit-image"><img src="https://i.redd.it/0mspe4sg07sf1.jpg" class="reddit-image"></div>   submitted by   <a href="https://www.reddit.com/user/grumpydogfather"> /u/grumpydogfather </a>   to   <a href="https://www.reddit.com/r/pics/"> r/pics </a> <br> <span><a href="https://www.reddit.com/gallery/1nty9r7">[link]</a></span>   <span><a href="https://www.reddit.com/r/pics/comments/1ntybco/oc_eastern_yellowbilled_hornbill/">[comments]</a></span>
 
 in /var/www/FreshRSS/extensions/xExtension-RedditImage-1.2.0/Content.php:28 Stack trace: 
 
 
 #0 /var/www/FreshRSS/extensions/xExtension-RedditImage-1.2.0/Processor/BeforeDisplayProcessor.php(46): RedditImage\Content->__construct() 
 #1 /var/www/FreshRSS/lib/Minz/ExtensionManager.php(422): RedditImage\Processor\BeforeDisplayProcessor->process() 
 #2 /var/www/FreshRSS/lib/Minz/ExtensionManager.php(389): Minz_ExtensionManager::callOneToOne() 
 #3 /var/www/FreshRSS/app/views/index/normal.phtml(50): Minz_ExtensionManager::callHook() 
 #4 /var/www/FreshRSS/lib/Minz/View.php(94): include('...') 
 #5 /var/www/FreshRSS/lib/Minz/View.php(116): Minz_View->includeFile() 
 #6 /var/www/FreshRSS/app/layout/layout.phtml(92): Minz_View->render() 
 #7 /var/www/FreshRSS/lib/Minz/View.php(94): include('...') 
 #8 /var/www/FreshRSS/lib/Minz/View.php(107): Minz_View->includeFile() 
 #9 /var/www/FreshRSS/lib/Minz/View.php(74): Minz_View->buildLayout() 
 #10 /var/www/FreshRSS/lib/Minz/Dispatcher.php(57): Minz_View->build() 
 #11 /var/www/FreshRSS/lib/Minz/FrontController.php(61): Minz_Dispatcher->run() 
 #12 /var/www/FreshRSS/p/i/index.php(58): Minz_FrontController->run() 
 #13 {main}
```

**Comment by aledeg** [comment]
Thank you for the trace. It helps a lot.

I think there is nothing I can do but remove the code since `reddit` changed how I can retrieve data. I'll look into it.
